[metadata]
name = pyrregular
author = Francesco Spinnato, Cristiano Landi
author_email = francesco.spinnato@unipi.it
description = Irregular time series in Python: datasets, classifiers and benchmarks (ICLR 2026)
keywords = irregular time series, irregularly sampled time series, time series classification, datasets, benchmark, missing data, xarray
url = https://github.com/fspinna/pyrregular
project_urls =
    Documentation = https://fspinna.github.io/pyrregular/
    Source = https://github.com/fspinna/pyrregular
    Paper = https://openreview.net/forum?id=qetBM8nLkf
    Datasets = https://huggingface.co/datasets/splandi/pyrregular
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13

[options]
packages = find:

install_requires =
    numpy
    numba
    pandas
    xarray
    sparse>=0.15.4
    h5py
    pyarrow
    pooch
    tqdm
    scikit-learn
    pyyaml
python_requires = >= 3.10

[options.extras_require]
dev =
    black
    mypy
    pre-commit
    pytest
    pytest-cov
docs =
    sphinx>=6.0
    myst-parser
    nbsphinx
    sphinx-autodoc-typehints
    sphinxcontrib-napoleon
    ipykernel
    nbconvert
    snowballstemmer<3.0.0
    sphinx-rtd-theme
    sphinx-sitemap
test =
    pytest
    pytest-cov
notebooks =
    notebook
borf =
    fast-borf>=0.2
    lightgbm
aeon =
    aeon
    lightgbm
sktime =
    sktime
    lightgbm
    tslearn
tslearn =
    tslearn
pypots =
    pypots
jax =
    jax
    equinox
    optax
    diffrax
models =
    fast-borf>=0.2
    lightgbm
    sktime
    aeon
    tslearn
    pypots
    jax
    equinox
    optax
    diffrax

[options.package_data]
pyrregular = registry.txt

[options.entry_points]
xarray.backends =
    pyrregular = pyrregular.backend:IrregularEntrypoint